spring:
  profiles:
    group:
      local:
        - local
        - aws
        - oauth
        - db
      prod :
        - aws
        - oauth
        - db
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL57Dialect
      format_sql: true
      default_batch_fetch_size: 100
    generate-ddl: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  devtools:
    livereload:
      enabled: 'true'
# server
server:
  address: localhost
  servlet:
    encoding:
      force: 'true'
      charset: UTF-8
      enabled: 'true'
    contextPath: /
  port: '8080'
build:
  date: '@build.date@'
# log
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      apache:
        tiles: INFO
      hibernate:
        SQL: DEBUG
    root: INFO
    com:
      samsung:
        security: DEBUG
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
  file:
    name: ./ssafy-web.log
